package com.woniu.pojo;
// Generated 2019-12-17 16:39:26 by Hibernate Tools 5.2.12.Final

/**
 * T1 generated by hbm2java
 */
@SuppressWarnings("serial")
public class T1 implements java.io.Serializable {

	private Integer id;
	private String name;

	public T1() {
	}

	public T1(String name) {
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
